title: ESP32 Nodes
description: ESP32 IoT gadgets
show_downloads: true
google_analytics:
theme: jekyll-theme-architect

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
