title: ESP32 Nodes
description: ESP32 IoT gadgets
show_downloads: true
google_analytics:
theme: jekyll-theme-architect

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

kramdown:
  syntax_highlighter: coderay

header_pages:
  - about.md

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
