// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#include "mongoose_glue.h"

#define WIFI_SSID "My_WiFi_Network"
#define WIFI_PASS "My_WiFi_Password"

extern void wifi_init(const char *ssid, const char *pass);

void app_main() {
  wifi_init(WIFI_SSID, WIFI_PASS); // This blocks until connected
  run_mongoose();
}
