repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: &excludes |
            (?x)^(
              .+\.(md|bin)|
              examples/stm32_example/.+
            )$
      - id: end-of-file-fixer
        exclude: *excludes
      - id: mixed-line-ending
        args: ['-f=lf']
        exclude: *excludes
  - repo: https://github.com/espressif/astyle_py.git
    rev: v1.0.5
    hooks:
      - id: astyle_py
        args: [--options=astyle_config]
        exclude: *excludes
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.9.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff # Runs ruff linter
        args: [--fix, --exit-non-zero-on-fix] # --fix for fixing errors
        types: [python]
      - id: ruff-format
        types: [python]
